veterinary-master/config/routes.rb
Veterinary::Application.routes.draw do

  root to: "users#index"

  resources :profiles

  resources :pet_types

  resources :appointments

  resources :pets

  resources :addresses

  devise_for :users

  resources :roles
  
  
  scope "/admin" do
    resources :users
  end

end

veterinary-master/app/controllers/pet_types_controller.rb
class PetTypesController < ApplicationController
  # GET /pet_types
  # GET /pet_types.json
   before_filter :authenticate_user!
  before_filter :authorize
  def index
    @pet_types = PetType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pet_types }
    end
  end

  # GET /pet_types/1
  # GET /pet_types/1.json
  def show
    @pet_type = PetType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pet_type }
    end
  end

  # GET /pet_types/new
  # GET /pet_types/new.json
  def new
    @pet_type = PetType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pet_type }
    end
  end

  # GET /pet_types/1/edit
  def edit
    @pet_type = PetType.find(params[:id])
  end

  # POST /pet_types
  # POST /pet_types.json
  def create
    @pet_type = PetType.new(params[:pet_type])

    respond_to do |format|
      if @pet_type.save
        format.html { redirect_to @pet_type, notice: 'Pet type was successfully created.' }
        format.json { render json: @pet_type, status: :created, location: @pet_type }
      else
        format.html { render action: "new" }
        format.json { render json: @pet_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pet_types/1
  # PUT /pet_types/1.json
  def update
    @pet_type = PetType.find(params[:id])

    respond_to do |format|
      if @pet_type.update_attributes(params[:pet_type])
        format.html { redirect_to @pet_type, notice: 'Pet type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pet_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pet_types/1
  # DELETE /pet_types/1.json
  def destroy
    @pet_type = PetType.find(params[:id])
    @pet_type.destroy

    respond_to do |format|
      format.html { redirect_to pet_types_url }
      format.json { head :no_content }
    end
  end
end

veterinary-master/app/helpers/pet_types_helper.rb
module PetTypesHelper
end

veterinary-master/app/views/pet_types/_form.html.erb
<%= form_for(@pet_type) do |f| %>
  <% if @pet_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet_type.errors.count, "error") %> prohibited this pet_type from being saved:</h2>

      <ul>
      <% @pet_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

veterinary-master/app/views/pet_types/edit.html.erb
<h1>Editing pet_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet_type %> |
<%= link_to 'Back', pet_types_path %>

veterinary-master/app/views/pet_types/index.html.erb
<h1>Listing pet_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pet_types.each do |pet_type| %>
  <tr>
    <td><%= pet_type.name %></td>
    <td><%= link_to 'Show', pet_type %></td>
    <td><%= link_to 'Edit', edit_pet_type_path(pet_type) %></td>
    <td><%= link_to 'Destroy', pet_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pet type', new_pet_type_path %>

veterinary-master/app/views/pet_types/new.html.erb
<h1>New pet_type</h1>

<%= render 'form' %>

<%= link_to 'Back', pet_types_path %>

veterinary-master/app/views/pet_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pet_type.name %>
</p>


<%= link_to 'Edit', edit_pet_type_path(@pet_type) %> |
<%= link_to 'Back', pet_types_path %>