veterinary-master/config/routes.rb
Veterinary::Application.routes.draw do

  root to: "users#index"

  resources :profiles

  resources :pet_types

  resources :appointments

  resources :pets

  resources :addresses

  devise_for :users

  resources :roles
  
  
  scope "/admin" do
    resources :users
  end

end

veterinary-master/app/models/appointment.rb
class Appointment < ActiveRecord::Base
  attr_accessible :date_of_visit, :doctor_id, :reminder, :pet_id, :reason, :user_id, :user_attributes, :pet_attributes
  belongs_to :user
  belongs_to :doctor, foreign_key: "doctor_id", class_name: "User"
  belongs_to :pet
  
  accepts_nested_attributes_for :user
  accepts_nested_attributes_for :user
  
  
  
end

veterinary-master/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  # GET /appointments
  # GET /appointments.json
  before_filter :authenticate_user!
  before_filter :authorize, except: [:index, :show]
  
  
  def index
    if current_user.customer?
      @appointments = current_user.appointments
    else
      @appointments = Appointment.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @appointments }
    end
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
    if current_user.customer?
      @appointment = current_user.appointments.find(params[:id])
    else
      @appointment = Appointment.find(params[:id])
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/new
  # GET /appointments/new.json
  def new
    @appointment = Appointment.new
    @doctors = User.doctors
    @user = @appointment.build_user
    @pet = @user.build_pet
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/1/edit
  def edit
    @appointment = Appointment.find(params[:id])
    @doctors = User.doctors
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(params[:appointment])

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render json: @appointment, status: :created, location: @appointment }
      else
        format.html { render action: "new" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /appointments/1
  # PUT /appointments/1.json
  def update
    @appointment = Appointment.find(params[:id])

    respond_to do |format|
      if @appointment.update_attributes(params[:appointment])
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end
end

veterinary-master/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

veterinary-master/app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_of_visit %><br />
    <%= f.datetime_select :date_of_visit %>
  </div>
	
	
	<div>
		<%= f.fields_for :user, @user  do |user| %>
			<%= render "/users/pet_form", :f => user  %>
		<% end %>
	</div>
	
  
  <div class="field">
    <%= f.label :reminder %><br />
    <%= f.datetime_select :reminder %>
  </div>
  <div class="field">
    <%= f.label :reason %><br />
    <%= f.text_area :reason %>
  </div>
  <div class="field">
    <%= f.label :doctor_id %><br />
		 <%= f.select :doctor_id, @doctors , {:prompt => 'Select Doctor'} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

veterinary-master/app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

veterinary-master/app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <tr>
    <th>Date of visit</th>
    <th>Pet</th>
    <th>User</th>
    <th>Minder</th>
    <th>Reason</th>
    <th>Doctor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @appointments.each do |appointment| %>
  <tr>
    <td><%= appointment.date_of_visit %></td>
    <td><%= appointment.user.pet.try(:name) %></td>
    <td><%= appointment.user.try(:name) %></td>
    <td><%= appointment.reminder %></td>
    <td><%= appointment.reason %></td>
    <td><%= appointment.doctor.try(:name) %></td>
		 <td><%= link_to 'Show', appointment %></td>
		<% unless current_user.customer? %>
   
    <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
    <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<% end %>
  </tr>
<% end %>
</table>

<br />
<% unless current_user.customer? %>
<%= link_to 'New Appointment', new_appointment_path %>
<% end %>

veterinary-master/app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

veterinary-master/app/views/appointments/show.html.erb
<% if current_user.customer?  %>
<p id="notice"><%= notice %></p>


<p>
  <b>Pet's Name:</b>
  <%= @appointment.user.pet.try(:name) %>
</p>


<p>
  <b>Date of visit:</b>
  <%= @appointment.date_of_visit %>
</p>

<p>
  <b>Pet:</b>
  <%= @appointment.pet.try(:name) %>
</p>

<p>
 <b>Reason:</b>
  <%= @appointment.reason %>
</p>


<% else %>

<p id="notice"><%= notice %></p>

<p>
  <b>Date of visit:</b>
  <%= @appointment.date_of_visit %>
</p>

<p>
  <b>Pet:</b>
  <%= @appointment.user.pet.try(:name) %>
</p>
<p>
	<%= link_to "Edit Pet Info", edit_pet_path(@appointment.user.pet.id)  %>
</p>

<p>
  <b>User:</b>
  <%= @appointment.user.try(:name) %>
</p>

<p>
  <b>Minder:</b>
  <%= @appointment.reminder %>
</p>

<p>
  <b>Reason:</b>
  <%= @appointment.reason %>
</p>

<p>
  <b>Doctor:</b>
  <%= @appointment.doctor.try(:name) %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

<% end %>